# Generated by Django 5.1.4 on 2025-01-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic_updated_by_topic_updated_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
