# Generated by Django 5.1.4 on 2025-01-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
